let obj = require('./Javascript Questions.js');
let Log = (input) => console.log(input);
console.clear();
Log(obj.findLongestSentence("Program to find longest word in a given sentence"));
Log(obj.isPalindrome("eve"));
Log(obj.isPalindrome("dany"));
Log(obj.removeDuplicates([1, 11, 2, 2, 33, 233, 5, 1]));
Log(obj.reverseString('dany'));
Log(obj.maxCountsOfConsecutiveOnesInArray([1, 11, 2, 33, 2, 4, 4, 2, 2]));
Log(obj.factorial(0));
Log(obj.factorial(5));
Log(obj.mergeSort([0, 3, 4, 31], [4, 6, 30]));
Log(obj.hasSquaredForAll([2, 4, 6], [4, 24, 6]));
Log(obj.hasSquaredForAll([2, 4, 6], [4, 24, 36]));
Log(obj.hasSquaredForAll([2, 4, 6], [4, 16, 36]));
Log(obj.getUniqueArray([{ name: 'Sai' }, { name: 'Nang' }, { name: 'sai' }, { name: 'Nang' }, { name: '111111' }]));
Log(obj.maxInArray([2, 333, 4, 1, 55, 76]));
Log(obj.getEvenNumbers([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]));
Log(obj.findLargestInNestedArray([[3, 4, 58], [709, 8, 9, [10, 11]], [111, 2]]));
Log(obj.findLargestInNestedArray([[2, 3, 111], [2, 7], 5, 8, [1212]]));
Log(obj.getArraySorted([244, 1, 2432, 11, 5], 'asc'));
Log(obj.getArraySorted([244, 1, 2432, 11, 5], 'desc'));
Log(obj.getArraySorted(['z','a','g','x','b'], 'desc'));
Log(obj.getArraySorted(['244', '1', '2432', '11', '5'], 'desc'));
Log(obj.flattenArray([1, [2, 3], [4, [5, 6]], 7], 2));
Log(obj.areStringsEqual('Danish', 'hsinad', true) ? 'strings are equal': 'strings are not equal');
Log(obj.areStringsEqual('Danish', 'hsinad', false) ? 'strings are equal': 'strings are not equal');
Log(obj.countCharacterOccurrences('Muhammad Danish farman'));
Log(obj.isPrime(20));
Log(obj.isPrime(7));
Log(obj.fibonacciNumbers(11));
Log(obj.reverseWords("This sentence will have words reversed in output!"));